package com.yunmu.core.model.contract;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContractExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    public ContractExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andContractNameIsNull() {
            addCriterion("contract_name is null");
            return (Criteria) this;
        }

        public Criteria andContractNameIsNotNull() {
            addCriterion("contract_name is not null");
            return (Criteria) this;
        }

        public Criteria andContractNameEqualTo(String value) {
            addCriterion("contract_name =", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotEqualTo(String value) {
            addCriterion("contract_name <>", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameGreaterThan(String value) {
            addCriterion("contract_name >", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameGreaterThanOrEqualTo(String value) {
            addCriterion("contract_name >=", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLessThan(String value) {
            addCriterion("contract_name <", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLessThanOrEqualTo(String value) {
            addCriterion("contract_name <=", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLike(String value) {
            addCriterion("contract_name like", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotLike(String value) {
            addCriterion("contract_name not like", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameIn(List<String> values) {
            addCriterion("contract_name in", values, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotIn(List<String> values) {
            addCriterion("contract_name not in", values, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameBetween(String value1, String value2) {
            addCriterion("contract_name between", value1, value2, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotBetween(String value1, String value2) {
            addCriterion("contract_name not between", value1, value2, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractTypeIsNull() {
            addCriterion("contract_type is null");
            return (Criteria) this;
        }

        public Criteria andContractTypeIsNotNull() {
            addCriterion("contract_type is not null");
            return (Criteria) this;
        }

        public Criteria andContractTypeEqualTo(Integer value) {
            addCriterion("contract_type =", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotEqualTo(Integer value) {
            addCriterion("contract_type <>", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeGreaterThan(Integer value) {
            addCriterion("contract_type >", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("contract_type >=", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLessThan(Integer value) {
            addCriterion("contract_type <", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLessThanOrEqualTo(Integer value) {
            addCriterion("contract_type <=", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeIn(List<Integer> values) {
            addCriterion("contract_type in", values, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotIn(List<Integer> values) {
            addCriterion("contract_type not in", values, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeBetween(Integer value1, Integer value2) {
            addCriterion("contract_type between", value1, value2, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("contract_type not between", value1, value2, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractCodeIsNull() {
            addCriterion("contract_code is null");
            return (Criteria) this;
        }

        public Criteria andContractCodeIsNotNull() {
            addCriterion("contract_code is not null");
            return (Criteria) this;
        }

        public Criteria andContractCodeEqualTo(String value) {
            addCriterion("contract_code =", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotEqualTo(String value) {
            addCriterion("contract_code <>", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeGreaterThan(String value) {
            addCriterion("contract_code >", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeGreaterThanOrEqualTo(String value) {
            addCriterion("contract_code >=", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeLessThan(String value) {
            addCriterion("contract_code <", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeLessThanOrEqualTo(String value) {
            addCriterion("contract_code <=", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeLike(String value) {
            addCriterion("contract_code like", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotLike(String value) {
            addCriterion("contract_code not like", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeIn(List<String> values) {
            addCriterion("contract_code in", values, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotIn(List<String> values) {
            addCriterion("contract_code not in", values, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeBetween(String value1, String value2) {
            addCriterion("contract_code between", value1, value2, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotBetween(String value1, String value2) {
            addCriterion("contract_code not between", value1, value2, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractIdentityIsNull() {
            addCriterion("contract_identity is null");
            return (Criteria) this;
        }

        public Criteria andContractIdentityIsNotNull() {
            addCriterion("contract_identity is not null");
            return (Criteria) this;
        }

        public Criteria andContractIdentityEqualTo(String value) {
            addCriterion("contract_identity =", value, "contractIdentity");
            return (Criteria) this;
        }

        public Criteria andContractIdentityNotEqualTo(String value) {
            addCriterion("contract_identity <>", value, "contractIdentity");
            return (Criteria) this;
        }

        public Criteria andContractIdentityGreaterThan(String value) {
            addCriterion("contract_identity >", value, "contractIdentity");
            return (Criteria) this;
        }

        public Criteria andContractIdentityGreaterThanOrEqualTo(String value) {
            addCriterion("contract_identity >=", value, "contractIdentity");
            return (Criteria) this;
        }

        public Criteria andContractIdentityLessThan(String value) {
            addCriterion("contract_identity <", value, "contractIdentity");
            return (Criteria) this;
        }

        public Criteria andContractIdentityLessThanOrEqualTo(String value) {
            addCriterion("contract_identity <=", value, "contractIdentity");
            return (Criteria) this;
        }

        public Criteria andContractIdentityLike(String value) {
            addCriterion("contract_identity like", value, "contractIdentity");
            return (Criteria) this;
        }

        public Criteria andContractIdentityNotLike(String value) {
            addCriterion("contract_identity not like", value, "contractIdentity");
            return (Criteria) this;
        }

        public Criteria andContractIdentityIn(List<String> values) {
            addCriterion("contract_identity in", values, "contractIdentity");
            return (Criteria) this;
        }

        public Criteria andContractIdentityNotIn(List<String> values) {
            addCriterion("contract_identity not in", values, "contractIdentity");
            return (Criteria) this;
        }

        public Criteria andContractIdentityBetween(String value1, String value2) {
            addCriterion("contract_identity between", value1, value2, "contractIdentity");
            return (Criteria) this;
        }

        public Criteria andContractIdentityNotBetween(String value1, String value2) {
            addCriterion("contract_identity not between", value1, value2, "contractIdentity");
            return (Criteria) this;
        }

        public Criteria andIdentityNameIsNull() {
            addCriterion("identity_name is null");
            return (Criteria) this;
        }

        public Criteria andIdentityNameIsNotNull() {
            addCriterion("identity_name is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityNameEqualTo(String value) {
            addCriterion("identity_name =", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameNotEqualTo(String value) {
            addCriterion("identity_name <>", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameGreaterThan(String value) {
            addCriterion("identity_name >", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameGreaterThanOrEqualTo(String value) {
            addCriterion("identity_name >=", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameLessThan(String value) {
            addCriterion("identity_name <", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameLessThanOrEqualTo(String value) {
            addCriterion("identity_name <=", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameLike(String value) {
            addCriterion("identity_name like", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameNotLike(String value) {
            addCriterion("identity_name not like", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameIn(List<String> values) {
            addCriterion("identity_name in", values, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameNotIn(List<String> values) {
            addCriterion("identity_name not in", values, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameBetween(String value1, String value2) {
            addCriterion("identity_name between", value1, value2, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameNotBetween(String value1, String value2) {
            addCriterion("identity_name not between", value1, value2, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityIdcardIsNull() {
            addCriterion("identity_IDcard is null");
            return (Criteria) this;
        }

        public Criteria andIdentityIdcardIsNotNull() {
            addCriterion("identity_IDcard is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityIdcardEqualTo(String value) {
            addCriterion("identity_IDcard =", value, "identityIdcard");
            return (Criteria) this;
        }

        public Criteria andIdentityIdcardNotEqualTo(String value) {
            addCriterion("identity_IDcard <>", value, "identityIdcard");
            return (Criteria) this;
        }

        public Criteria andIdentityIdcardGreaterThan(String value) {
            addCriterion("identity_IDcard >", value, "identityIdcard");
            return (Criteria) this;
        }

        public Criteria andIdentityIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("identity_IDcard >=", value, "identityIdcard");
            return (Criteria) this;
        }

        public Criteria andIdentityIdcardLessThan(String value) {
            addCriterion("identity_IDcard <", value, "identityIdcard");
            return (Criteria) this;
        }

        public Criteria andIdentityIdcardLessThanOrEqualTo(String value) {
            addCriterion("identity_IDcard <=", value, "identityIdcard");
            return (Criteria) this;
        }

        public Criteria andIdentityIdcardLike(String value) {
            addCriterion("identity_IDcard like", value, "identityIdcard");
            return (Criteria) this;
        }

        public Criteria andIdentityIdcardNotLike(String value) {
            addCriterion("identity_IDcard not like", value, "identityIdcard");
            return (Criteria) this;
        }

        public Criteria andIdentityIdcardIn(List<String> values) {
            addCriterion("identity_IDcard in", values, "identityIdcard");
            return (Criteria) this;
        }

        public Criteria andIdentityIdcardNotIn(List<String> values) {
            addCriterion("identity_IDcard not in", values, "identityIdcard");
            return (Criteria) this;
        }

        public Criteria andIdentityIdcardBetween(String value1, String value2) {
            addCriterion("identity_IDcard between", value1, value2, "identityIdcard");
            return (Criteria) this;
        }

        public Criteria andIdentityIdcardNotBetween(String value1, String value2) {
            addCriterion("identity_IDcard not between", value1, value2, "identityIdcard");
            return (Criteria) this;
        }

        public Criteria andIndentityTelIsNull() {
            addCriterion("indentity_tel is null");
            return (Criteria) this;
        }

        public Criteria andIndentityTelIsNotNull() {
            addCriterion("indentity_tel is not null");
            return (Criteria) this;
        }

        public Criteria andIndentityTelEqualTo(String value) {
            addCriterion("indentity_tel =", value, "indentityTel");
            return (Criteria) this;
        }

        public Criteria andIndentityTelNotEqualTo(String value) {
            addCriterion("indentity_tel <>", value, "indentityTel");
            return (Criteria) this;
        }

        public Criteria andIndentityTelGreaterThan(String value) {
            addCriterion("indentity_tel >", value, "indentityTel");
            return (Criteria) this;
        }

        public Criteria andIndentityTelGreaterThanOrEqualTo(String value) {
            addCriterion("indentity_tel >=", value, "indentityTel");
            return (Criteria) this;
        }

        public Criteria andIndentityTelLessThan(String value) {
            addCriterion("indentity_tel <", value, "indentityTel");
            return (Criteria) this;
        }

        public Criteria andIndentityTelLessThanOrEqualTo(String value) {
            addCriterion("indentity_tel <=", value, "indentityTel");
            return (Criteria) this;
        }

        public Criteria andIndentityTelLike(String value) {
            addCriterion("indentity_tel like", value, "indentityTel");
            return (Criteria) this;
        }

        public Criteria andIndentityTelNotLike(String value) {
            addCriterion("indentity_tel not like", value, "indentityTel");
            return (Criteria) this;
        }

        public Criteria andIndentityTelIn(List<String> values) {
            addCriterion("indentity_tel in", values, "indentityTel");
            return (Criteria) this;
        }

        public Criteria andIndentityTelNotIn(List<String> values) {
            addCriterion("indentity_tel not in", values, "indentityTel");
            return (Criteria) this;
        }

        public Criteria andIndentityTelBetween(String value1, String value2) {
            addCriterion("indentity_tel between", value1, value2, "indentityTel");
            return (Criteria) this;
        }

        public Criteria andIndentityTelNotBetween(String value1, String value2) {
            addCriterion("indentity_tel not between", value1, value2, "indentityTel");
            return (Criteria) this;
        }

        public Criteria andContractStatusIsNull() {
            addCriterion("contract_status is null");
            return (Criteria) this;
        }

        public Criteria andContractStatusIsNotNull() {
            addCriterion("contract_status is not null");
            return (Criteria) this;
        }

        public Criteria andContractStatusEqualTo(Integer value) {
            addCriterion("contract_status =", value, "contractStatus");
            return (Criteria) this;
        }

        public Criteria andContractStatusNotEqualTo(Integer value) {
            addCriterion("contract_status <>", value, "contractStatus");
            return (Criteria) this;
        }

        public Criteria andContractStatusGreaterThan(Integer value) {
            addCriterion("contract_status >", value, "contractStatus");
            return (Criteria) this;
        }

        public Criteria andContractStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("contract_status >=", value, "contractStatus");
            return (Criteria) this;
        }

        public Criteria andContractStatusLessThan(Integer value) {
            addCriterion("contract_status <", value, "contractStatus");
            return (Criteria) this;
        }

        public Criteria andContractStatusLessThanOrEqualTo(Integer value) {
            addCriterion("contract_status <=", value, "contractStatus");
            return (Criteria) this;
        }

        public Criteria andContractStatusIn(List<Integer> values) {
            addCriterion("contract_status in", values, "contractStatus");
            return (Criteria) this;
        }

        public Criteria andContractStatusNotIn(List<Integer> values) {
            addCriterion("contract_status not in", values, "contractStatus");
            return (Criteria) this;
        }

        public Criteria andContractStatusBetween(Integer value1, Integer value2) {
            addCriterion("contract_status between", value1, value2, "contractStatus");
            return (Criteria) this;
        }

        public Criteria andContractStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("contract_status not between", value1, value2, "contractStatus");
            return (Criteria) this;
        }

        public Criteria andContractExcuteIsNull() {
            addCriterion("contract_excute is null");
            return (Criteria) this;
        }

        public Criteria andContractExcuteIsNotNull() {
            addCriterion("contract_excute is not null");
            return (Criteria) this;
        }

        public Criteria andContractExcuteEqualTo(String value) {
            addCriterion("contract_excute =", value, "contractExcute");
            return (Criteria) this;
        }

        public Criteria andContractExcuteNotEqualTo(String value) {
            addCriterion("contract_excute <>", value, "contractExcute");
            return (Criteria) this;
        }

        public Criteria andContractExcuteGreaterThan(String value) {
            addCriterion("contract_excute >", value, "contractExcute");
            return (Criteria) this;
        }

        public Criteria andContractExcuteGreaterThanOrEqualTo(String value) {
            addCriterion("contract_excute >=", value, "contractExcute");
            return (Criteria) this;
        }

        public Criteria andContractExcuteLessThan(String value) {
            addCriterion("contract_excute <", value, "contractExcute");
            return (Criteria) this;
        }

        public Criteria andContractExcuteLessThanOrEqualTo(String value) {
            addCriterion("contract_excute <=", value, "contractExcute");
            return (Criteria) this;
        }

        public Criteria andContractExcuteLike(String value) {
            addCriterion("contract_excute like", value, "contractExcute");
            return (Criteria) this;
        }

        public Criteria andContractExcuteNotLike(String value) {
            addCriterion("contract_excute not like", value, "contractExcute");
            return (Criteria) this;
        }

        public Criteria andContractExcuteIn(List<String> values) {
            addCriterion("contract_excute in", values, "contractExcute");
            return (Criteria) this;
        }

        public Criteria andContractExcuteNotIn(List<String> values) {
            addCriterion("contract_excute not in", values, "contractExcute");
            return (Criteria) this;
        }

        public Criteria andContractExcuteBetween(String value1, String value2) {
            addCriterion("contract_excute between", value1, value2, "contractExcute");
            return (Criteria) this;
        }

        public Criteria andContractExcuteNotBetween(String value1, String value2) {
            addCriterion("contract_excute not between", value1, value2, "contractExcute");
            return (Criteria) this;
        }

        public Criteria andExcuteIdcardIsNull() {
            addCriterion("excute_IDcard is null");
            return (Criteria) this;
        }

        public Criteria andExcuteIdcardIsNotNull() {
            addCriterion("excute_IDcard is not null");
            return (Criteria) this;
        }

        public Criteria andExcuteIdcardEqualTo(String value) {
            addCriterion("excute_IDcard =", value, "excuteIdcard");
            return (Criteria) this;
        }

        public Criteria andExcuteIdcardNotEqualTo(String value) {
            addCriterion("excute_IDcard <>", value, "excuteIdcard");
            return (Criteria) this;
        }

        public Criteria andExcuteIdcardGreaterThan(String value) {
            addCriterion("excute_IDcard >", value, "excuteIdcard");
            return (Criteria) this;
        }

        public Criteria andExcuteIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("excute_IDcard >=", value, "excuteIdcard");
            return (Criteria) this;
        }

        public Criteria andExcuteIdcardLessThan(String value) {
            addCriterion("excute_IDcard <", value, "excuteIdcard");
            return (Criteria) this;
        }

        public Criteria andExcuteIdcardLessThanOrEqualTo(String value) {
            addCriterion("excute_IDcard <=", value, "excuteIdcard");
            return (Criteria) this;
        }

        public Criteria andExcuteIdcardLike(String value) {
            addCriterion("excute_IDcard like", value, "excuteIdcard");
            return (Criteria) this;
        }

        public Criteria andExcuteIdcardNotLike(String value) {
            addCriterion("excute_IDcard not like", value, "excuteIdcard");
            return (Criteria) this;
        }

        public Criteria andExcuteIdcardIn(List<String> values) {
            addCriterion("excute_IDcard in", values, "excuteIdcard");
            return (Criteria) this;
        }

        public Criteria andExcuteIdcardNotIn(List<String> values) {
            addCriterion("excute_IDcard not in", values, "excuteIdcard");
            return (Criteria) this;
        }

        public Criteria andExcuteIdcardBetween(String value1, String value2) {
            addCriterion("excute_IDcard between", value1, value2, "excuteIdcard");
            return (Criteria) this;
        }

        public Criteria andExcuteIdcardNotBetween(String value1, String value2) {
            addCriterion("excute_IDcard not between", value1, value2, "excuteIdcard");
            return (Criteria) this;
        }

        public Criteria andExcuteProxyIsNull() {
            addCriterion("excute_proxy is null");
            return (Criteria) this;
        }

        public Criteria andExcuteProxyIsNotNull() {
            addCriterion("excute_proxy is not null");
            return (Criteria) this;
        }

        public Criteria andExcuteProxyEqualTo(String value) {
            addCriterion("excute_proxy =", value, "excuteProxy");
            return (Criteria) this;
        }

        public Criteria andExcuteProxyNotEqualTo(String value) {
            addCriterion("excute_proxy <>", value, "excuteProxy");
            return (Criteria) this;
        }

        public Criteria andExcuteProxyGreaterThan(String value) {
            addCriterion("excute_proxy >", value, "excuteProxy");
            return (Criteria) this;
        }

        public Criteria andExcuteProxyGreaterThanOrEqualTo(String value) {
            addCriterion("excute_proxy >=", value, "excuteProxy");
            return (Criteria) this;
        }

        public Criteria andExcuteProxyLessThan(String value) {
            addCriterion("excute_proxy <", value, "excuteProxy");
            return (Criteria) this;
        }

        public Criteria andExcuteProxyLessThanOrEqualTo(String value) {
            addCriterion("excute_proxy <=", value, "excuteProxy");
            return (Criteria) this;
        }

        public Criteria andExcuteProxyLike(String value) {
            addCriterion("excute_proxy like", value, "excuteProxy");
            return (Criteria) this;
        }

        public Criteria andExcuteProxyNotLike(String value) {
            addCriterion("excute_proxy not like", value, "excuteProxy");
            return (Criteria) this;
        }

        public Criteria andExcuteProxyIn(List<String> values) {
            addCriterion("excute_proxy in", values, "excuteProxy");
            return (Criteria) this;
        }

        public Criteria andExcuteProxyNotIn(List<String> values) {
            addCriterion("excute_proxy not in", values, "excuteProxy");
            return (Criteria) this;
        }

        public Criteria andExcuteProxyBetween(String value1, String value2) {
            addCriterion("excute_proxy between", value1, value2, "excuteProxy");
            return (Criteria) this;
        }

        public Criteria andExcuteProxyNotBetween(String value1, String value2) {
            addCriterion("excute_proxy not between", value1, value2, "excuteProxy");
            return (Criteria) this;
        }

        public Criteria andExcuteTelIsNull() {
            addCriterion("excute_tel is null");
            return (Criteria) this;
        }

        public Criteria andExcuteTelIsNotNull() {
            addCriterion("excute_tel is not null");
            return (Criteria) this;
        }

        public Criteria andExcuteTelEqualTo(String value) {
            addCriterion("excute_tel =", value, "excuteTel");
            return (Criteria) this;
        }

        public Criteria andExcuteTelNotEqualTo(String value) {
            addCriterion("excute_tel <>", value, "excuteTel");
            return (Criteria) this;
        }

        public Criteria andExcuteTelGreaterThan(String value) {
            addCriterion("excute_tel >", value, "excuteTel");
            return (Criteria) this;
        }

        public Criteria andExcuteTelGreaterThanOrEqualTo(String value) {
            addCriterion("excute_tel >=", value, "excuteTel");
            return (Criteria) this;
        }

        public Criteria andExcuteTelLessThan(String value) {
            addCriterion("excute_tel <", value, "excuteTel");
            return (Criteria) this;
        }

        public Criteria andExcuteTelLessThanOrEqualTo(String value) {
            addCriterion("excute_tel <=", value, "excuteTel");
            return (Criteria) this;
        }

        public Criteria andExcuteTelLike(String value) {
            addCriterion("excute_tel like", value, "excuteTel");
            return (Criteria) this;
        }

        public Criteria andExcuteTelNotLike(String value) {
            addCriterion("excute_tel not like", value, "excuteTel");
            return (Criteria) this;
        }

        public Criteria andExcuteTelIn(List<String> values) {
            addCriterion("excute_tel in", values, "excuteTel");
            return (Criteria) this;
        }

        public Criteria andExcuteTelNotIn(List<String> values) {
            addCriterion("excute_tel not in", values, "excuteTel");
            return (Criteria) this;
        }

        public Criteria andExcuteTelBetween(String value1, String value2) {
            addCriterion("excute_tel between", value1, value2, "excuteTel");
            return (Criteria) this;
        }

        public Criteria andExcuteTelNotBetween(String value1, String value2) {
            addCriterion("excute_tel not between", value1, value2, "excuteTel");
            return (Criteria) this;
        }

        public Criteria andExcuteEmailIsNull() {
            addCriterion("excute_email is null");
            return (Criteria) this;
        }

        public Criteria andExcuteEmailIsNotNull() {
            addCriterion("excute_email is not null");
            return (Criteria) this;
        }

        public Criteria andExcuteEmailEqualTo(String value) {
            addCriterion("excute_email =", value, "excuteEmail");
            return (Criteria) this;
        }

        public Criteria andExcuteEmailNotEqualTo(String value) {
            addCriterion("excute_email <>", value, "excuteEmail");
            return (Criteria) this;
        }

        public Criteria andExcuteEmailGreaterThan(String value) {
            addCriterion("excute_email >", value, "excuteEmail");
            return (Criteria) this;
        }

        public Criteria andExcuteEmailGreaterThanOrEqualTo(String value) {
            addCriterion("excute_email >=", value, "excuteEmail");
            return (Criteria) this;
        }

        public Criteria andExcuteEmailLessThan(String value) {
            addCriterion("excute_email <", value, "excuteEmail");
            return (Criteria) this;
        }

        public Criteria andExcuteEmailLessThanOrEqualTo(String value) {
            addCriterion("excute_email <=", value, "excuteEmail");
            return (Criteria) this;
        }

        public Criteria andExcuteEmailLike(String value) {
            addCriterion("excute_email like", value, "excuteEmail");
            return (Criteria) this;
        }

        public Criteria andExcuteEmailNotLike(String value) {
            addCriterion("excute_email not like", value, "excuteEmail");
            return (Criteria) this;
        }

        public Criteria andExcuteEmailIn(List<String> values) {
            addCriterion("excute_email in", values, "excuteEmail");
            return (Criteria) this;
        }

        public Criteria andExcuteEmailNotIn(List<String> values) {
            addCriterion("excute_email not in", values, "excuteEmail");
            return (Criteria) this;
        }

        public Criteria andExcuteEmailBetween(String value1, String value2) {
            addCriterion("excute_email between", value1, value2, "excuteEmail");
            return (Criteria) this;
        }

        public Criteria andExcuteEmailNotBetween(String value1, String value2) {
            addCriterion("excute_email not between", value1, value2, "excuteEmail");
            return (Criteria) this;
        }

        public Criteria andExcuteAddrIsNull() {
            addCriterion("excute_addr is null");
            return (Criteria) this;
        }

        public Criteria andExcuteAddrIsNotNull() {
            addCriterion("excute_addr is not null");
            return (Criteria) this;
        }

        public Criteria andExcuteAddrEqualTo(String value) {
            addCriterion("excute_addr =", value, "excuteAddr");
            return (Criteria) this;
        }

        public Criteria andExcuteAddrNotEqualTo(String value) {
            addCriterion("excute_addr <>", value, "excuteAddr");
            return (Criteria) this;
        }

        public Criteria andExcuteAddrGreaterThan(String value) {
            addCriterion("excute_addr >", value, "excuteAddr");
            return (Criteria) this;
        }

        public Criteria andExcuteAddrGreaterThanOrEqualTo(String value) {
            addCriterion("excute_addr >=", value, "excuteAddr");
            return (Criteria) this;
        }

        public Criteria andExcuteAddrLessThan(String value) {
            addCriterion("excute_addr <", value, "excuteAddr");
            return (Criteria) this;
        }

        public Criteria andExcuteAddrLessThanOrEqualTo(String value) {
            addCriterion("excute_addr <=", value, "excuteAddr");
            return (Criteria) this;
        }

        public Criteria andExcuteAddrLike(String value) {
            addCriterion("excute_addr like", value, "excuteAddr");
            return (Criteria) this;
        }

        public Criteria andExcuteAddrNotLike(String value) {
            addCriterion("excute_addr not like", value, "excuteAddr");
            return (Criteria) this;
        }

        public Criteria andExcuteAddrIn(List<String> values) {
            addCriterion("excute_addr in", values, "excuteAddr");
            return (Criteria) this;
        }

        public Criteria andExcuteAddrNotIn(List<String> values) {
            addCriterion("excute_addr not in", values, "excuteAddr");
            return (Criteria) this;
        }

        public Criteria andExcuteAddrBetween(String value1, String value2) {
            addCriterion("excute_addr between", value1, value2, "excuteAddr");
            return (Criteria) this;
        }

        public Criteria andExcuteAddrNotBetween(String value1, String value2) {
            addCriterion("excute_addr not between", value1, value2, "excuteAddr");
            return (Criteria) this;
        }

        public Criteria andExcuteOpeningBankIsNull() {
            addCriterion("excute_opening_bank is null");
            return (Criteria) this;
        }

        public Criteria andExcuteOpeningBankIsNotNull() {
            addCriterion("excute_opening_bank is not null");
            return (Criteria) this;
        }

        public Criteria andExcuteOpeningBankEqualTo(String value) {
            addCriterion("excute_opening_bank =", value, "excuteOpeningBank");
            return (Criteria) this;
        }

        public Criteria andExcuteOpeningBankNotEqualTo(String value) {
            addCriterion("excute_opening_bank <>", value, "excuteOpeningBank");
            return (Criteria) this;
        }

        public Criteria andExcuteOpeningBankGreaterThan(String value) {
            addCriterion("excute_opening_bank >", value, "excuteOpeningBank");
            return (Criteria) this;
        }

        public Criteria andExcuteOpeningBankGreaterThanOrEqualTo(String value) {
            addCriterion("excute_opening_bank >=", value, "excuteOpeningBank");
            return (Criteria) this;
        }

        public Criteria andExcuteOpeningBankLessThan(String value) {
            addCriterion("excute_opening_bank <", value, "excuteOpeningBank");
            return (Criteria) this;
        }

        public Criteria andExcuteOpeningBankLessThanOrEqualTo(String value) {
            addCriterion("excute_opening_bank <=", value, "excuteOpeningBank");
            return (Criteria) this;
        }

        public Criteria andExcuteOpeningBankLike(String value) {
            addCriterion("excute_opening_bank like", value, "excuteOpeningBank");
            return (Criteria) this;
        }

        public Criteria andExcuteOpeningBankNotLike(String value) {
            addCriterion("excute_opening_bank not like", value, "excuteOpeningBank");
            return (Criteria) this;
        }

        public Criteria andExcuteOpeningBankIn(List<String> values) {
            addCriterion("excute_opening_bank in", values, "excuteOpeningBank");
            return (Criteria) this;
        }

        public Criteria andExcuteOpeningBankNotIn(List<String> values) {
            addCriterion("excute_opening_bank not in", values, "excuteOpeningBank");
            return (Criteria) this;
        }

        public Criteria andExcuteOpeningBankBetween(String value1, String value2) {
            addCriterion("excute_opening_bank between", value1, value2, "excuteOpeningBank");
            return (Criteria) this;
        }

        public Criteria andExcuteOpeningBankNotBetween(String value1, String value2) {
            addCriterion("excute_opening_bank not between", value1, value2, "excuteOpeningBank");
            return (Criteria) this;
        }

        public Criteria andBanksNameIsNull() {
            addCriterion("banks_name is null");
            return (Criteria) this;
        }

        public Criteria andBanksNameIsNotNull() {
            addCriterion("banks_name is not null");
            return (Criteria) this;
        }

        public Criteria andBanksNameEqualTo(String value) {
            addCriterion("banks_name =", value, "banksName");
            return (Criteria) this;
        }

        public Criteria andBanksNameNotEqualTo(String value) {
            addCriterion("banks_name <>", value, "banksName");
            return (Criteria) this;
        }

        public Criteria andBanksNameGreaterThan(String value) {
            addCriterion("banks_name >", value, "banksName");
            return (Criteria) this;
        }

        public Criteria andBanksNameGreaterThanOrEqualTo(String value) {
            addCriterion("banks_name >=", value, "banksName");
            return (Criteria) this;
        }

        public Criteria andBanksNameLessThan(String value) {
            addCriterion("banks_name <", value, "banksName");
            return (Criteria) this;
        }

        public Criteria andBanksNameLessThanOrEqualTo(String value) {
            addCriterion("banks_name <=", value, "banksName");
            return (Criteria) this;
        }

        public Criteria andBanksNameLike(String value) {
            addCriterion("banks_name like", value, "banksName");
            return (Criteria) this;
        }

        public Criteria andBanksNameNotLike(String value) {
            addCriterion("banks_name not like", value, "banksName");
            return (Criteria) this;
        }

        public Criteria andBanksNameIn(List<String> values) {
            addCriterion("banks_name in", values, "banksName");
            return (Criteria) this;
        }

        public Criteria andBanksNameNotIn(List<String> values) {
            addCriterion("banks_name not in", values, "banksName");
            return (Criteria) this;
        }

        public Criteria andBanksNameBetween(String value1, String value2) {
            addCriterion("banks_name between", value1, value2, "banksName");
            return (Criteria) this;
        }

        public Criteria andBanksNameNotBetween(String value1, String value2) {
            addCriterion("banks_name not between", value1, value2, "banksName");
            return (Criteria) this;
        }

        public Criteria andBankNumberIsNull() {
            addCriterion("bank_number is null");
            return (Criteria) this;
        }

        public Criteria andBankNumberIsNotNull() {
            addCriterion("bank_number is not null");
            return (Criteria) this;
        }

        public Criteria andBankNumberEqualTo(String value) {
            addCriterion("bank_number =", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberNotEqualTo(String value) {
            addCriterion("bank_number <>", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberGreaterThan(String value) {
            addCriterion("bank_number >", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberGreaterThanOrEqualTo(String value) {
            addCriterion("bank_number >=", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberLessThan(String value) {
            addCriterion("bank_number <", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberLessThanOrEqualTo(String value) {
            addCriterion("bank_number <=", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberLike(String value) {
            addCriterion("bank_number like", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberNotLike(String value) {
            addCriterion("bank_number not like", value, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberIn(List<String> values) {
            addCriterion("bank_number in", values, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberNotIn(List<String> values) {
            addCriterion("bank_number not in", values, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberBetween(String value1, String value2) {
            addCriterion("bank_number between", value1, value2, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andBankNumberNotBetween(String value1, String value2) {
            addCriterion("bank_number not between", value1, value2, "bankNumber");
            return (Criteria) this;
        }

        public Criteria andContractAddrIsNull() {
            addCriterion("contract_addr is null");
            return (Criteria) this;
        }

        public Criteria andContractAddrIsNotNull() {
            addCriterion("contract_addr is not null");
            return (Criteria) this;
        }

        public Criteria andContractAddrEqualTo(String value) {
            addCriterion("contract_addr =", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrNotEqualTo(String value) {
            addCriterion("contract_addr <>", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrGreaterThan(String value) {
            addCriterion("contract_addr >", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrGreaterThanOrEqualTo(String value) {
            addCriterion("contract_addr >=", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrLessThan(String value) {
            addCriterion("contract_addr <", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrLessThanOrEqualTo(String value) {
            addCriterion("contract_addr <=", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrLike(String value) {
            addCriterion("contract_addr like", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrNotLike(String value) {
            addCriterion("contract_addr not like", value, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrIn(List<String> values) {
            addCriterion("contract_addr in", values, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrNotIn(List<String> values) {
            addCriterion("contract_addr not in", values, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrBetween(String value1, String value2) {
            addCriterion("contract_addr between", value1, value2, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andContractAddrNotBetween(String value1, String value2) {
            addCriterion("contract_addr not between", value1, value2, "contractAddr");
            return (Criteria) this;
        }

        public Criteria andHourseAreaIsNull() {
            addCriterion("hourse_area is null");
            return (Criteria) this;
        }

        public Criteria andHourseAreaIsNotNull() {
            addCriterion("hourse_area is not null");
            return (Criteria) this;
        }

        public Criteria andHourseAreaEqualTo(Float value) {
            addCriterion("hourse_area =", value, "hourseArea");
            return (Criteria) this;
        }

        public Criteria andHourseAreaNotEqualTo(Float value) {
            addCriterion("hourse_area <>", value, "hourseArea");
            return (Criteria) this;
        }

        public Criteria andHourseAreaGreaterThan(Float value) {
            addCriterion("hourse_area >", value, "hourseArea");
            return (Criteria) this;
        }

        public Criteria andHourseAreaGreaterThanOrEqualTo(Float value) {
            addCriterion("hourse_area >=", value, "hourseArea");
            return (Criteria) this;
        }

        public Criteria andHourseAreaLessThan(Float value) {
            addCriterion("hourse_area <", value, "hourseArea");
            return (Criteria) this;
        }

        public Criteria andHourseAreaLessThanOrEqualTo(Float value) {
            addCriterion("hourse_area <=", value, "hourseArea");
            return (Criteria) this;
        }

        public Criteria andHourseAreaIn(List<Float> values) {
            addCriterion("hourse_area in", values, "hourseArea");
            return (Criteria) this;
        }

        public Criteria andHourseAreaNotIn(List<Float> values) {
            addCriterion("hourse_area not in", values, "hourseArea");
            return (Criteria) this;
        }

        public Criteria andHourseAreaBetween(Float value1, Float value2) {
            addCriterion("hourse_area between", value1, value2, "hourseArea");
            return (Criteria) this;
        }

        public Criteria andHourseAreaNotBetween(Float value1, Float value2) {
            addCriterion("hourse_area not between", value1, value2, "hourseArea");
            return (Criteria) this;
        }

        public Criteria andHourseAddrIsNull() {
            addCriterion("hourse_addr is null");
            return (Criteria) this;
        }

        public Criteria andHourseAddrIsNotNull() {
            addCriterion("hourse_addr is not null");
            return (Criteria) this;
        }

        public Criteria andHourseAddrEqualTo(String value) {
            addCriterion("hourse_addr =", value, "hourseAddr");
            return (Criteria) this;
        }

        public Criteria andHourseAddrNotEqualTo(String value) {
            addCriterion("hourse_addr <>", value, "hourseAddr");
            return (Criteria) this;
        }

        public Criteria andHourseAddrGreaterThan(String value) {
            addCriterion("hourse_addr >", value, "hourseAddr");
            return (Criteria) this;
        }

        public Criteria andHourseAddrGreaterThanOrEqualTo(String value) {
            addCriterion("hourse_addr >=", value, "hourseAddr");
            return (Criteria) this;
        }

        public Criteria andHourseAddrLessThan(String value) {
            addCriterion("hourse_addr <", value, "hourseAddr");
            return (Criteria) this;
        }

        public Criteria andHourseAddrLessThanOrEqualTo(String value) {
            addCriterion("hourse_addr <=", value, "hourseAddr");
            return (Criteria) this;
        }

        public Criteria andHourseAddrLike(String value) {
            addCriterion("hourse_addr like", value, "hourseAddr");
            return (Criteria) this;
        }

        public Criteria andHourseAddrNotLike(String value) {
            addCriterion("hourse_addr not like", value, "hourseAddr");
            return (Criteria) this;
        }

        public Criteria andHourseAddrIn(List<String> values) {
            addCriterion("hourse_addr in", values, "hourseAddr");
            return (Criteria) this;
        }

        public Criteria andHourseAddrNotIn(List<String> values) {
            addCriterion("hourse_addr not in", values, "hourseAddr");
            return (Criteria) this;
        }

        public Criteria andHourseAddrBetween(String value1, String value2) {
            addCriterion("hourse_addr between", value1, value2, "hourseAddr");
            return (Criteria) this;
        }

        public Criteria andHourseAddrNotBetween(String value1, String value2) {
            addCriterion("hourse_addr not between", value1, value2, "hourseAddr");
            return (Criteria) this;
        }

        public Criteria andHourseUsesIsNull() {
            addCriterion("hourse_uses is null");
            return (Criteria) this;
        }

        public Criteria andHourseUsesIsNotNull() {
            addCriterion("hourse_uses is not null");
            return (Criteria) this;
        }

        public Criteria andHourseUsesEqualTo(String value) {
            addCriterion("hourse_uses =", value, "hourseUses");
            return (Criteria) this;
        }

        public Criteria andHourseUsesNotEqualTo(String value) {
            addCriterion("hourse_uses <>", value, "hourseUses");
            return (Criteria) this;
        }

        public Criteria andHourseUsesGreaterThan(String value) {
            addCriterion("hourse_uses >", value, "hourseUses");
            return (Criteria) this;
        }

        public Criteria andHourseUsesGreaterThanOrEqualTo(String value) {
            addCriterion("hourse_uses >=", value, "hourseUses");
            return (Criteria) this;
        }

        public Criteria andHourseUsesLessThan(String value) {
            addCriterion("hourse_uses <", value, "hourseUses");
            return (Criteria) this;
        }

        public Criteria andHourseUsesLessThanOrEqualTo(String value) {
            addCriterion("hourse_uses <=", value, "hourseUses");
            return (Criteria) this;
        }

        public Criteria andHourseUsesLike(String value) {
            addCriterion("hourse_uses like", value, "hourseUses");
            return (Criteria) this;
        }

        public Criteria andHourseUsesNotLike(String value) {
            addCriterion("hourse_uses not like", value, "hourseUses");
            return (Criteria) this;
        }

        public Criteria andHourseUsesIn(List<String> values) {
            addCriterion("hourse_uses in", values, "hourseUses");
            return (Criteria) this;
        }

        public Criteria andHourseUsesNotIn(List<String> values) {
            addCriterion("hourse_uses not in", values, "hourseUses");
            return (Criteria) this;
        }

        public Criteria andHourseUsesBetween(String value1, String value2) {
            addCriterion("hourse_uses between", value1, value2, "hourseUses");
            return (Criteria) this;
        }

        public Criteria andHourseUsesNotBetween(String value1, String value2) {
            addCriterion("hourse_uses not between", value1, value2, "hourseUses");
            return (Criteria) this;
        }

        public Criteria andOperativeWayIsNull() {
            addCriterion("operative_way is null");
            return (Criteria) this;
        }

        public Criteria andOperativeWayIsNotNull() {
            addCriterion("operative_way is not null");
            return (Criteria) this;
        }

        public Criteria andOperativeWayEqualTo(String value) {
            addCriterion("operative_way =", value, "operativeWay");
            return (Criteria) this;
        }

        public Criteria andOperativeWayNotEqualTo(String value) {
            addCriterion("operative_way <>", value, "operativeWay");
            return (Criteria) this;
        }

        public Criteria andOperativeWayGreaterThan(String value) {
            addCriterion("operative_way >", value, "operativeWay");
            return (Criteria) this;
        }

        public Criteria andOperativeWayGreaterThanOrEqualTo(String value) {
            addCriterion("operative_way >=", value, "operativeWay");
            return (Criteria) this;
        }

        public Criteria andOperativeWayLessThan(String value) {
            addCriterion("operative_way <", value, "operativeWay");
            return (Criteria) this;
        }

        public Criteria andOperativeWayLessThanOrEqualTo(String value) {
            addCriterion("operative_way <=", value, "operativeWay");
            return (Criteria) this;
        }

        public Criteria andOperativeWayLike(String value) {
            addCriterion("operative_way like", value, "operativeWay");
            return (Criteria) this;
        }

        public Criteria andOperativeWayNotLike(String value) {
            addCriterion("operative_way not like", value, "operativeWay");
            return (Criteria) this;
        }

        public Criteria andOperativeWayIn(List<String> values) {
            addCriterion("operative_way in", values, "operativeWay");
            return (Criteria) this;
        }

        public Criteria andOperativeWayNotIn(List<String> values) {
            addCriterion("operative_way not in", values, "operativeWay");
            return (Criteria) this;
        }

        public Criteria andOperativeWayBetween(String value1, String value2) {
            addCriterion("operative_way between", value1, value2, "operativeWay");
            return (Criteria) this;
        }

        public Criteria andOperativeWayNotBetween(String value1, String value2) {
            addCriterion("operative_way not between", value1, value2, "operativeWay");
            return (Criteria) this;
        }

        public Criteria andContractStartTimeIsNull() {
            addCriterion("contract_start_time is null");
            return (Criteria) this;
        }

        public Criteria andContractStartTimeIsNotNull() {
            addCriterion("contract_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andContractStartTimeEqualTo(Date value) {
            addCriterion("contract_start_time =", value, "contractStartTime");
            return (Criteria) this;
        }

        public Criteria andContractStartTimeNotEqualTo(Date value) {
            addCriterion("contract_start_time <>", value, "contractStartTime");
            return (Criteria) this;
        }

        public Criteria andContractStartTimeGreaterThan(Date value) {
            addCriterion("contract_start_time >", value, "contractStartTime");
            return (Criteria) this;
        }

        public Criteria andContractStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("contract_start_time >=", value, "contractStartTime");
            return (Criteria) this;
        }

        public Criteria andContractStartTimeLessThan(Date value) {
            addCriterion("contract_start_time <", value, "contractStartTime");
            return (Criteria) this;
        }

        public Criteria andContractStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("contract_start_time <=", value, "contractStartTime");
            return (Criteria) this;
        }

        public Criteria andContractStartTimeIn(List<Date> values) {
            addCriterion("contract_start_time in", values, "contractStartTime");
            return (Criteria) this;
        }

        public Criteria andContractStartTimeNotIn(List<Date> values) {
            addCriterion("contract_start_time not in", values, "contractStartTime");
            return (Criteria) this;
        }

        public Criteria andContractStartTimeBetween(Date value1, Date value2) {
            addCriterion("contract_start_time between", value1, value2, "contractStartTime");
            return (Criteria) this;
        }

        public Criteria andContractStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("contract_start_time not between", value1, value2, "contractStartTime");
            return (Criteria) this;
        }

        public Criteria andContractEndTimeIsNull() {
            addCriterion("contract_end_time is null");
            return (Criteria) this;
        }

        public Criteria andContractEndTimeIsNotNull() {
            addCriterion("contract_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andContractEndTimeEqualTo(Date value) {
            addCriterion("contract_end_time =", value, "contractEndTime");
            return (Criteria) this;
        }

        public Criteria andContractEndTimeNotEqualTo(Date value) {
            addCriterion("contract_end_time <>", value, "contractEndTime");
            return (Criteria) this;
        }

        public Criteria andContractEndTimeGreaterThan(Date value) {
            addCriterion("contract_end_time >", value, "contractEndTime");
            return (Criteria) this;
        }

        public Criteria andContractEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("contract_end_time >=", value, "contractEndTime");
            return (Criteria) this;
        }

        public Criteria andContractEndTimeLessThan(Date value) {
            addCriterion("contract_end_time <", value, "contractEndTime");
            return (Criteria) this;
        }

        public Criteria andContractEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("contract_end_time <=", value, "contractEndTime");
            return (Criteria) this;
        }

        public Criteria andContractEndTimeIn(List<Date> values) {
            addCriterion("contract_end_time in", values, "contractEndTime");
            return (Criteria) this;
        }

        public Criteria andContractEndTimeNotIn(List<Date> values) {
            addCriterion("contract_end_time not in", values, "contractEndTime");
            return (Criteria) this;
        }

        public Criteria andContractEndTimeBetween(Date value1, Date value2) {
            addCriterion("contract_end_time between", value1, value2, "contractEndTime");
            return (Criteria) this;
        }

        public Criteria andContractEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("contract_end_time not between", value1, value2, "contractEndTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andContractDescIsNull() {
            addCriterion("contract_desc is null");
            return (Criteria) this;
        }

        public Criteria andContractDescIsNotNull() {
            addCriterion("contract_desc is not null");
            return (Criteria) this;
        }

        public Criteria andContractDescEqualTo(String value) {
            addCriterion("contract_desc =", value, "contractDesc");
            return (Criteria) this;
        }

        public Criteria andContractDescNotEqualTo(String value) {
            addCriterion("contract_desc <>", value, "contractDesc");
            return (Criteria) this;
        }

        public Criteria andContractDescGreaterThan(String value) {
            addCriterion("contract_desc >", value, "contractDesc");
            return (Criteria) this;
        }

        public Criteria andContractDescGreaterThanOrEqualTo(String value) {
            addCriterion("contract_desc >=", value, "contractDesc");
            return (Criteria) this;
        }

        public Criteria andContractDescLessThan(String value) {
            addCriterion("contract_desc <", value, "contractDesc");
            return (Criteria) this;
        }

        public Criteria andContractDescLessThanOrEqualTo(String value) {
            addCriterion("contract_desc <=", value, "contractDesc");
            return (Criteria) this;
        }

        public Criteria andContractDescLike(String value) {
            addCriterion("contract_desc like", value, "contractDesc");
            return (Criteria) this;
        }

        public Criteria andContractDescNotLike(String value) {
            addCriterion("contract_desc not like", value, "contractDesc");
            return (Criteria) this;
        }

        public Criteria andContractDescIn(List<String> values) {
            addCriterion("contract_desc in", values, "contractDesc");
            return (Criteria) this;
        }

        public Criteria andContractDescNotIn(List<String> values) {
            addCriterion("contract_desc not in", values, "contractDesc");
            return (Criteria) this;
        }

        public Criteria andContractDescBetween(String value1, String value2) {
            addCriterion("contract_desc between", value1, value2, "contractDesc");
            return (Criteria) this;
        }

        public Criteria andContractDescNotBetween(String value1, String value2) {
            addCriterion("contract_desc not between", value1, value2, "contractDesc");
            return (Criteria) this;
        }

        public Criteria andRentFreeCountIsNull() {
            addCriterion("rent_free_count is null");
            return (Criteria) this;
        }

        public Criteria andRentFreeCountIsNotNull() {
            addCriterion("rent_free_count is not null");
            return (Criteria) this;
        }

        public Criteria andRentFreeCountEqualTo(Integer value) {
            addCriterion("rent_free_count =", value, "rentFreeCount");
            return (Criteria) this;
        }

        public Criteria andRentFreeCountNotEqualTo(Integer value) {
            addCriterion("rent_free_count <>", value, "rentFreeCount");
            return (Criteria) this;
        }

        public Criteria andRentFreeCountGreaterThan(Integer value) {
            addCriterion("rent_free_count >", value, "rentFreeCount");
            return (Criteria) this;
        }

        public Criteria andRentFreeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("rent_free_count >=", value, "rentFreeCount");
            return (Criteria) this;
        }

        public Criteria andRentFreeCountLessThan(Integer value) {
            addCriterion("rent_free_count <", value, "rentFreeCount");
            return (Criteria) this;
        }

        public Criteria andRentFreeCountLessThanOrEqualTo(Integer value) {
            addCriterion("rent_free_count <=", value, "rentFreeCount");
            return (Criteria) this;
        }

        public Criteria andRentFreeCountIn(List<Integer> values) {
            addCriterion("rent_free_count in", values, "rentFreeCount");
            return (Criteria) this;
        }

        public Criteria andRentFreeCountNotIn(List<Integer> values) {
            addCriterion("rent_free_count not in", values, "rentFreeCount");
            return (Criteria) this;
        }

        public Criteria andRentFreeCountBetween(Integer value1, Integer value2) {
            addCriterion("rent_free_count between", value1, value2, "rentFreeCount");
            return (Criteria) this;
        }

        public Criteria andRentFreeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("rent_free_count not between", value1, value2, "rentFreeCount");
            return (Criteria) this;
        }

        public Criteria andRentAmountIsNull() {
            addCriterion("rent_amount is null");
            return (Criteria) this;
        }

        public Criteria andRentAmountIsNotNull() {
            addCriterion("rent_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRentAmountEqualTo(Long value) {
            addCriterion("rent_amount =", value, "rentAmount");
            return (Criteria) this;
        }

        public Criteria andRentAmountNotEqualTo(Long value) {
            addCriterion("rent_amount <>", value, "rentAmount");
            return (Criteria) this;
        }

        public Criteria andRentAmountGreaterThan(Long value) {
            addCriterion("rent_amount >", value, "rentAmount");
            return (Criteria) this;
        }

        public Criteria andRentAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("rent_amount >=", value, "rentAmount");
            return (Criteria) this;
        }

        public Criteria andRentAmountLessThan(Long value) {
            addCriterion("rent_amount <", value, "rentAmount");
            return (Criteria) this;
        }

        public Criteria andRentAmountLessThanOrEqualTo(Long value) {
            addCriterion("rent_amount <=", value, "rentAmount");
            return (Criteria) this;
        }

        public Criteria andRentAmountIn(List<Long> values) {
            addCriterion("rent_amount in", values, "rentAmount");
            return (Criteria) this;
        }

        public Criteria andRentAmountNotIn(List<Long> values) {
            addCriterion("rent_amount not in", values, "rentAmount");
            return (Criteria) this;
        }

        public Criteria andRentAmountBetween(Long value1, Long value2) {
            addCriterion("rent_amount between", value1, value2, "rentAmount");
            return (Criteria) this;
        }

        public Criteria andRentAmountNotBetween(Long value1, Long value2) {
            addCriterion("rent_amount not between", value1, value2, "rentAmount");
            return (Criteria) this;
        }

        public Criteria andRentFreeStartTimeIsNull() {
            addCriterion("rent_free_start_time is null");
            return (Criteria) this;
        }

        public Criteria andRentFreeStartTimeIsNotNull() {
            addCriterion("rent_free_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andRentFreeStartTimeEqualTo(Date value) {
            addCriterion("rent_free_start_time =", value, "rentFreeStartTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeStartTimeNotEqualTo(Date value) {
            addCriterion("rent_free_start_time <>", value, "rentFreeStartTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeStartTimeGreaterThan(Date value) {
            addCriterion("rent_free_start_time >", value, "rentFreeStartTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("rent_free_start_time >=", value, "rentFreeStartTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeStartTimeLessThan(Date value) {
            addCriterion("rent_free_start_time <", value, "rentFreeStartTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("rent_free_start_time <=", value, "rentFreeStartTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeStartTimeIn(List<Date> values) {
            addCriterion("rent_free_start_time in", values, "rentFreeStartTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeStartTimeNotIn(List<Date> values) {
            addCriterion("rent_free_start_time not in", values, "rentFreeStartTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeStartTimeBetween(Date value1, Date value2) {
            addCriterion("rent_free_start_time between", value1, value2, "rentFreeStartTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("rent_free_start_time not between", value1, value2, "rentFreeStartTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeEndTimeIsNull() {
            addCriterion("rent_free_end_time is null");
            return (Criteria) this;
        }

        public Criteria andRentFreeEndTimeIsNotNull() {
            addCriterion("rent_free_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andRentFreeEndTimeEqualTo(Date value) {
            addCriterion("rent_free_end_time =", value, "rentFreeEndTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeEndTimeNotEqualTo(Date value) {
            addCriterion("rent_free_end_time <>", value, "rentFreeEndTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeEndTimeGreaterThan(Date value) {
            addCriterion("rent_free_end_time >", value, "rentFreeEndTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("rent_free_end_time >=", value, "rentFreeEndTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeEndTimeLessThan(Date value) {
            addCriterion("rent_free_end_time <", value, "rentFreeEndTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("rent_free_end_time <=", value, "rentFreeEndTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeEndTimeIn(List<Date> values) {
            addCriterion("rent_free_end_time in", values, "rentFreeEndTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeEndTimeNotIn(List<Date> values) {
            addCriterion("rent_free_end_time not in", values, "rentFreeEndTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeEndTimeBetween(Date value1, Date value2) {
            addCriterion("rent_free_end_time between", value1, value2, "rentFreeEndTime");
            return (Criteria) this;
        }

        public Criteria andRentFreeEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("rent_free_end_time not between", value1, value2, "rentFreeEndTime");
            return (Criteria) this;
        }

        public Criteria andRentIncreaseWayIsNull() {
            addCriterion("rent_increase_way is null");
            return (Criteria) this;
        }

        public Criteria andRentIncreaseWayIsNotNull() {
            addCriterion("rent_increase_way is not null");
            return (Criteria) this;
        }

        public Criteria andRentIncreaseWayEqualTo(String value) {
            addCriterion("rent_increase_way =", value, "rentIncreaseWay");
            return (Criteria) this;
        }

        public Criteria andRentIncreaseWayNotEqualTo(String value) {
            addCriterion("rent_increase_way <>", value, "rentIncreaseWay");
            return (Criteria) this;
        }

        public Criteria andRentIncreaseWayGreaterThan(String value) {
            addCriterion("rent_increase_way >", value, "rentIncreaseWay");
            return (Criteria) this;
        }

        public Criteria andRentIncreaseWayGreaterThanOrEqualTo(String value) {
            addCriterion("rent_increase_way >=", value, "rentIncreaseWay");
            return (Criteria) this;
        }

        public Criteria andRentIncreaseWayLessThan(String value) {
            addCriterion("rent_increase_way <", value, "rentIncreaseWay");
            return (Criteria) this;
        }

        public Criteria andRentIncreaseWayLessThanOrEqualTo(String value) {
            addCriterion("rent_increase_way <=", value, "rentIncreaseWay");
            return (Criteria) this;
        }

        public Criteria andRentIncreaseWayLike(String value) {
            addCriterion("rent_increase_way like", value, "rentIncreaseWay");
            return (Criteria) this;
        }

        public Criteria andRentIncreaseWayNotLike(String value) {
            addCriterion("rent_increase_way not like", value, "rentIncreaseWay");
            return (Criteria) this;
        }

        public Criteria andRentIncreaseWayIn(List<String> values) {
            addCriterion("rent_increase_way in", values, "rentIncreaseWay");
            return (Criteria) this;
        }

        public Criteria andRentIncreaseWayNotIn(List<String> values) {
            addCriterion("rent_increase_way not in", values, "rentIncreaseWay");
            return (Criteria) this;
        }

        public Criteria andRentIncreaseWayBetween(String value1, String value2) {
            addCriterion("rent_increase_way between", value1, value2, "rentIncreaseWay");
            return (Criteria) this;
        }

        public Criteria andRentIncreaseWayNotBetween(String value1, String value2) {
            addCriterion("rent_increase_way not between", value1, value2, "rentIncreaseWay");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andContractTimeIsNull() {
            addCriterion("contract_time is null");
            return (Criteria) this;
        }

        public Criteria andContractTimeIsNotNull() {
            addCriterion("contract_time is not null");
            return (Criteria) this;
        }

        public Criteria andContractTimeEqualTo(Date value) {
            addCriterion("contract_time =", value, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeNotEqualTo(Date value) {
            addCriterion("contract_time <>", value, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeGreaterThan(Date value) {
            addCriterion("contract_time >", value, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("contract_time >=", value, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeLessThan(Date value) {
            addCriterion("contract_time <", value, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeLessThanOrEqualTo(Date value) {
            addCriterion("contract_time <=", value, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeIn(List<Date> values) {
            addCriterion("contract_time in", values, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeNotIn(List<Date> values) {
            addCriterion("contract_time not in", values, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeBetween(Date value1, Date value2) {
            addCriterion("contract_time between", value1, value2, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeNotBetween(Date value1, Date value2) {
            addCriterion("contract_time not between", value1, value2, "contractTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yunmu_contract
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}