package com.yunmu.core.model.contract;

import java.io.Serializable;
import java.util.Date;

public class ContractExt implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.project_id
     *
     * @mbggenerated
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.contract_name
     *
     * @mbggenerated
     */
    private String contractName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.contract_type
     *
     * @mbggenerated
     */
    private Integer contractType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.contract_code
     *
     * @mbggenerated
     */
    private String contractCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.contract_identity
     *
     * @mbggenerated
     */
    private String contractIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.identity_name
     *
     * @mbggenerated
     */
    private String identityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.identity_IDcard
     *
     * @mbggenerated
     */
    private String identityIdcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.indentity_tel
     *
     * @mbggenerated
     */
    private String indentityTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.contract_status
     *
     * @mbggenerated
     */
    private Integer contractStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.contract_excute
     *
     * @mbggenerated
     */
    private String contractExcute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.excute_IDcard
     *
     * @mbggenerated
     */
    private String excuteIdcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.excute_proxy
     *
     * @mbggenerated
     */
    private String excuteProxy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.excute_tel
     *
     * @mbggenerated
     */
    private String excuteTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.excute_email
     *
     * @mbggenerated
     */
    private String excuteEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.excute_addr
     *
     * @mbggenerated
     */
    private String excuteAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.excute_opening_bank
     *
     * @mbggenerated
     */
    private String excuteOpeningBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.banks_name
     *
     * @mbggenerated
     */
    private String banksName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.bank_number
     *
     * @mbggenerated
     */
    private String bankNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.contract_addr
     *
     * @mbggenerated
     */
    private String contractAddr;

    private String operaterBy;

    private String typeName;

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public String getOperaterBy() {
        return operaterBy;
    }

    public void setOperaterBy(String operaterBy) {
        this.operaterBy = operaterBy;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.hourse_area
     *
     * @mbggenerated
     */
    private Float hourseArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.hourse_addr
     *
     * @mbggenerated
     */
    private String hourseAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.hourse_uses
     *
     * @mbggenerated
     */
    private String hourseUses;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.operative_way
     *
     * @mbggenerated
     */
    private String operativeWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.contract_start_time
     *
     * @mbggenerated
     */
    private Date contractStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.contract_end_time
     *
     * @mbggenerated
     */
    private Date contractEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.contract_desc
     *
     * @mbggenerated
     */
    private String contractDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.rent_free_count
     *
     * @mbggenerated
     */
    private Integer rentFreeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.rent_amount
     *
     * @mbggenerated
     */
    private Long rentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.rent_free_start_time
     *
     * @mbggenerated
     */
    private Date rentFreeStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.rent_free_end_time
     *
     * @mbggenerated
     */
    private Date rentFreeEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.rent_increase_way
     *
     * @mbggenerated
     */
    private String rentIncreaseWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.contract_time
     *
     * @mbggenerated
     */
    private Date contractTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.contract_entrust
     *
     * @mbggenerated
     */
    private String contractEntrust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.entrust_IDcard
     *
     * @mbggenerated
     */
    private String entrustIdcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.entrust_proxy
     *
     * @mbggenerated
     */
    private String entrustProxy;

    public String getContractEntrust() {
        return contractEntrust;
    }

    public void setContractEntrust(String contractEntrust) {
        this.contractEntrust = contractEntrust;
    }

    public String getEntrustIdcard() {
        return entrustIdcard;
    }

    public void setEntrustIdcard(String entrustIdcard) {
        this.entrustIdcard = entrustIdcard;
    }

    public String getEntrustProxy() {
        return entrustProxy;
    }

    public void setEntrustProxy(String entrustProxy) {
        this.entrustProxy = entrustProxy;
    }

    public String getEntrustTel() {
        return entrustTel;
    }

    public void setEntrustTel(String entrustTel) {
        this.entrustTel = entrustTel;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunmu_contract.entrust_tel
     *
     * @mbggenerated
     */
    private String entrustTel;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yunmu_contract
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.id
     *
     * @return the value of yunmu_contract.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.id
     *
     * @param id the value for yunmu_contract.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.project_id
     *
     * @return the value of yunmu_contract.project_id
     *
     * @mbggenerated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.project_id
     *
     * @param projectId the value for yunmu_contract.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.contract_name
     *
     * @return the value of yunmu_contract.contract_name
     *
     * @mbggenerated
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.contract_name
     *
     * @param contractName the value for yunmu_contract.contract_name
     *
     * @mbggenerated
     */
    public void setContractName(String contractName) {
        this.contractName = contractName == null ? null : contractName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.contract_type
     *
     * @return the value of yunmu_contract.contract_type
     *
     * @mbggenerated
     */
    public Integer getContractType() {
        return contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.contract_type
     *
     * @param contractType the value for yunmu_contract.contract_type
     *
     * @mbggenerated
     */
    public void setContractType(Integer contractType) {
        this.contractType = contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.contract_code
     *
     * @return the value of yunmu_contract.contract_code
     *
     * @mbggenerated
     */
    public String getContractCode() {
        return contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.contract_code
     *
     * @param contractCode the value for yunmu_contract.contract_code
     *
     * @mbggenerated
     */
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode == null ? null : contractCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.contract_identity
     *
     * @return the value of yunmu_contract.contract_identity
     *
     * @mbggenerated
     */
    public String getContractIdentity() {
        return contractIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.contract_identity
     *
     * @param contractIdentity the value for yunmu_contract.contract_identity
     *
     * @mbggenerated
     */
    public void setContractIdentity(String contractIdentity) {
        this.contractIdentity = contractIdentity == null ? null : contractIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.identity_name
     *
     * @return the value of yunmu_contract.identity_name
     *
     * @mbggenerated
     */
    public String getIdentityName() {
        return identityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.identity_name
     *
     * @param identityName the value for yunmu_contract.identity_name
     *
     * @mbggenerated
     */
    public void setIdentityName(String identityName) {
        this.identityName = identityName == null ? null : identityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.identity_IDcard
     *
     * @return the value of yunmu_contract.identity_IDcard
     *
     * @mbggenerated
     */
    public String getIdentityIdcard() {
        return identityIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.identity_IDcard
     *
     * @param identityIdcard the value for yunmu_contract.identity_IDcard
     *
     * @mbggenerated
     */
    public void setIdentityIdcard(String identityIdcard) {
        this.identityIdcard = identityIdcard == null ? null : identityIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.indentity_tel
     *
     * @return the value of yunmu_contract.indentity_tel
     *
     * @mbggenerated
     */
    public String getIndentityTel() {
        return indentityTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.indentity_tel
     *
     * @param indentityTel the value for yunmu_contract.indentity_tel
     *
     * @mbggenerated
     */
    public void setIndentityTel(String indentityTel) {
        this.indentityTel = indentityTel == null ? null : indentityTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.contract_status
     *
     * @return the value of yunmu_contract.contract_status
     *
     * @mbggenerated
     */
    public Integer getContractStatus() {
        return contractStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.contract_status
     *
     * @param contractStatus the value for yunmu_contract.contract_status
     *
     * @mbggenerated
     */
    public void setContractStatus(Integer contractStatus) {
        this.contractStatus = contractStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.contract_excute
     *
     * @return the value of yunmu_contract.contract_excute
     *
     * @mbggenerated
     */
    public String getContractExcute() {
        return contractExcute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.contract_excute
     *
     * @param contractExcute the value for yunmu_contract.contract_excute
     *
     * @mbggenerated
     */
    public void setContractExcute(String contractExcute) {
        this.contractExcute = contractExcute == null ? null : contractExcute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.excute_IDcard
     *
     * @return the value of yunmu_contract.excute_IDcard
     *
     * @mbggenerated
     */
    public String getExcuteIdcard() {
        return excuteIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.excute_IDcard
     *
     * @param excuteIdcard the value for yunmu_contract.excute_IDcard
     *
     * @mbggenerated
     */
    public void setExcuteIdcard(String excuteIdcard) {
        this.excuteIdcard = excuteIdcard == null ? null : excuteIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.excute_proxy
     *
     * @return the value of yunmu_contract.excute_proxy
     *
     * @mbggenerated
     */
    public String getExcuteProxy() {
        return excuteProxy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.excute_proxy
     *
     * @param excuteProxy the value for yunmu_contract.excute_proxy
     *
     * @mbggenerated
     */
    public void setExcuteProxy(String excuteProxy) {
        this.excuteProxy = excuteProxy == null ? null : excuteProxy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.excute_tel
     *
     * @return the value of yunmu_contract.excute_tel
     *
     * @mbggenerated
     */
    public String getExcuteTel() {
        return excuteTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.excute_tel
     *
     * @param excuteTel the value for yunmu_contract.excute_tel
     *
     * @mbggenerated
     */
    public void setExcuteTel(String excuteTel) {
        this.excuteTel = excuteTel == null ? null : excuteTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.excute_email
     *
     * @return the value of yunmu_contract.excute_email
     *
     * @mbggenerated
     */
    public String getExcuteEmail() {
        return excuteEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.excute_email
     *
     * @param excuteEmail the value for yunmu_contract.excute_email
     *
     * @mbggenerated
     */
    public void setExcuteEmail(String excuteEmail) {
        this.excuteEmail = excuteEmail == null ? null : excuteEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.excute_addr
     *
     * @return the value of yunmu_contract.excute_addr
     *
     * @mbggenerated
     */
    public String getExcuteAddr() {
        return excuteAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.excute_addr
     *
     * @param excuteAddr the value for yunmu_contract.excute_addr
     *
     * @mbggenerated
     */
    public void setExcuteAddr(String excuteAddr) {
        this.excuteAddr = excuteAddr == null ? null : excuteAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.excute_opening_bank
     *
     * @return the value of yunmu_contract.excute_opening_bank
     *
     * @mbggenerated
     */
    public String getExcuteOpeningBank() {
        return excuteOpeningBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.excute_opening_bank
     *
     * @param excuteOpeningBank the value for yunmu_contract.excute_opening_bank
     *
     * @mbggenerated
     */
    public void setExcuteOpeningBank(String excuteOpeningBank) {
        this.excuteOpeningBank = excuteOpeningBank == null ? null : excuteOpeningBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.banks_name
     *
     * @return the value of yunmu_contract.banks_name
     *
     * @mbggenerated
     */
    public String getBanksName() {
        return banksName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.banks_name
     *
     * @param banksName the value for yunmu_contract.banks_name
     *
     * @mbggenerated
     */
    public void setBanksName(String banksName) {
        this.banksName = banksName == null ? null : banksName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.bank_number
     *
     * @return the value of yunmu_contract.bank_number
     *
     * @mbggenerated
     */
    public String getBankNumber() {
        return bankNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.bank_number
     *
     * @param bankNumber the value for yunmu_contract.bank_number
     *
     * @mbggenerated
     */
    public void setBankNumber(String bankNumber) {
        this.bankNumber = bankNumber == null ? null : bankNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.contract_addr
     *
     * @return the value of yunmu_contract.contract_addr
     *
     * @mbggenerated
     */
    public String getContractAddr() {
        return contractAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.contract_addr
     *
     * @param contractAddr the value for yunmu_contract.contract_addr
     *
     * @mbggenerated
     */
    public void setContractAddr(String contractAddr) {
        this.contractAddr = contractAddr == null ? null : contractAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.hourse_area
     *
     * @return the value of yunmu_contract.hourse_area
     *
     * @mbggenerated
     */
    public Float getHourseArea() {
        return hourseArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.hourse_area
     *
     * @param hourseArea the value for yunmu_contract.hourse_area
     *
     * @mbggenerated
     */
    public void setHourseArea(Float hourseArea) {
        this.hourseArea = hourseArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.hourse_addr
     *
     * @return the value of yunmu_contract.hourse_addr
     *
     * @mbggenerated
     */
    public String getHourseAddr() {
        return hourseAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.hourse_addr
     *
     * @param hourseAddr the value for yunmu_contract.hourse_addr
     *
     * @mbggenerated
     */
    public void setHourseAddr(String hourseAddr) {
        this.hourseAddr = hourseAddr == null ? null : hourseAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.hourse_uses
     *
     * @return the value of yunmu_contract.hourse_uses
     *
     * @mbggenerated
     */
    public String getHourseUses() {
        return hourseUses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.hourse_uses
     *
     * @param hourseUses the value for yunmu_contract.hourse_uses
     *
     * @mbggenerated
     */
    public void setHourseUses(String hourseUses) {
        this.hourseUses = hourseUses == null ? null : hourseUses.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.operative_way
     *
     * @return the value of yunmu_contract.operative_way
     *
     * @mbggenerated
     */
    public String getOperativeWay() {
        return operativeWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.operative_way
     *
     * @param operativeWay the value for yunmu_contract.operative_way
     *
     * @mbggenerated
     */
    public void setOperativeWay(String operativeWay) {
        this.operativeWay = operativeWay == null ? null : operativeWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.contract_start_time
     *
     * @return the value of yunmu_contract.contract_start_time
     *
     * @mbggenerated
     */
    public Date getContractStartTime() {
        return contractStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.contract_start_time
     *
     * @param contractStartTime the value for yunmu_contract.contract_start_time
     *
     * @mbggenerated
     */
    public void setContractStartTime(Date contractStartTime) {
        this.contractStartTime = contractStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.contract_end_time
     *
     * @return the value of yunmu_contract.contract_end_time
     *
     * @mbggenerated
     */
    public Date getContractEndTime() {
        return contractEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.contract_end_time
     *
     * @param contractEndTime the value for yunmu_contract.contract_end_time
     *
     * @mbggenerated
     */
    public void setContractEndTime(Date contractEndTime) {
        this.contractEndTime = contractEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.create_time
     *
     * @return the value of yunmu_contract.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.create_time
     *
     * @param createTime the value for yunmu_contract.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.create_by
     *
     * @return the value of yunmu_contract.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.create_by
     *
     * @param createBy the value for yunmu_contract.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.update_time
     *
     * @return the value of yunmu_contract.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.update_time
     *
     * @param updateTime the value for yunmu_contract.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.update_by
     *
     * @return the value of yunmu_contract.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.update_by
     *
     * @param updateBy the value for yunmu_contract.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.contract_desc
     *
     * @return the value of yunmu_contract.contract_desc
     *
     * @mbggenerated
     */
    public String getContractDesc() {
        return contractDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.contract_desc
     *
     * @param contractDesc the value for yunmu_contract.contract_desc
     *
     * @mbggenerated
     */
    public void setContractDesc(String contractDesc) {
        this.contractDesc = contractDesc == null ? null : contractDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.rent_free_count
     *
     * @return the value of yunmu_contract.rent_free_count
     *
     * @mbggenerated
     */
    public Integer getRentFreeCount() {
        return rentFreeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.rent_free_count
     *
     * @param rentFreeCount the value for yunmu_contract.rent_free_count
     *
     * @mbggenerated
     */
    public void setRentFreeCount(Integer rentFreeCount) {
        this.rentFreeCount = rentFreeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.rent_amount
     *
     * @return the value of yunmu_contract.rent_amount
     *
     * @mbggenerated
     */
    public Long getRentAmount() {
        return rentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.rent_amount
     *
     * @param rentAmount the value for yunmu_contract.rent_amount
     *
     * @mbggenerated
     */
    public void setRentAmount(Long rentAmount) {
        this.rentAmount = rentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.rent_free_start_time
     *
     * @return the value of yunmu_contract.rent_free_start_time
     *
     * @mbggenerated
     */
    public Date getRentFreeStartTime() {
        return rentFreeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.rent_free_start_time
     *
     * @param rentFreeStartTime the value for yunmu_contract.rent_free_start_time
     *
     * @mbggenerated
     */
    public void setRentFreeStartTime(Date rentFreeStartTime) {
        this.rentFreeStartTime = rentFreeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.rent_free_end_time
     *
     * @return the value of yunmu_contract.rent_free_end_time
     *
     * @mbggenerated
     */
    public Date getRentFreeEndTime() {
        return rentFreeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.rent_free_end_time
     *
     * @param rentFreeEndTime the value for yunmu_contract.rent_free_end_time
     *
     * @mbggenerated
     */
    public void setRentFreeEndTime(Date rentFreeEndTime) {
        this.rentFreeEndTime = rentFreeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.rent_increase_way
     *
     * @return the value of yunmu_contract.rent_increase_way
     *
     * @mbggenerated
     */
    public String getRentIncreaseWay() {
        return rentIncreaseWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.rent_increase_way
     *
     * @param rentIncreaseWay the value for yunmu_contract.rent_increase_way
     *
     * @mbggenerated
     */
    public void setRentIncreaseWay(String rentIncreaseWay) {
        this.rentIncreaseWay = rentIncreaseWay == null ? null : rentIncreaseWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.del_flag
     *
     * @return the value of yunmu_contract.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.del_flag
     *
     * @param delFlag the value for yunmu_contract.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunmu_contract.contract_time
     *
     * @return the value of yunmu_contract.contract_time
     *
     * @mbggenerated
     */
    public Date getContractTime() {
        return contractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunmu_contract.contract_time
     *
     * @param contractTime the value for yunmu_contract.contract_time
     *
     * @mbggenerated
     */
    public void setContractTime(Date contractTime) {
        this.contractTime = contractTime;
    }
}